<?php

namespace Hs\PhoneBookBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array|null
     */
    public function getPersonsWithPhones()
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.phones', 'c')
            ->addSelect('c')
            ->getQuery();

        try {
            return $query->getResult();
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }

    /**
     * @param $id
     * @return array|null
     */
    public function getPersonPhones($id){
        $query = $this->createQueryBuilder('p')
            ->join('p.persons', 'c')
            ->addSelect('p')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        try {
            return $query->getResult();
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }

    public function updateRelation(){

    }
}
