<?php

namespace Hs\PhoneBookBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends \Doctrine\ORM\EntityRepository
{

}








